# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{digest_mailer}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sean Zehnder"]
  s.date = %q{2011-04-28}
  s.description = %q{Provides a digest functionality for our application leveraging delayed_job and action_mailer}
  s.email = %q{szehnder@victorsandspoils.com}
  s.extra_rdoc_files = [
    "README.textile"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE",
    "README.textile",
    "Rakefile",
    "VERSION",
    "autotest/discover.rb",
    "config/database.yml",
    "digest_mailer.gemspec",
    "digest_mailer_test.log",
    "lib/digest_mailer.rb",
    "lib/digest_mailer/generators/digest_mailer/digest_mailer_generator.rb",
    "lib/digest_mailer/generators/digest_mailer/templates/migration.rb",
    "lib/digest_mailer/layout/html_digest_layout.rb",
    "lib/digest_mailer/layout/text_digest_layout.rb",
    "lib/digest_mailer/mail_delayed_job_scheduler.rb",
    "lib/digest_mailer/mail_dispatcher.rb",
    "lib/digest_mailer/mail_logger.rb",
    "lib/digest_mailer/mail_orchestrator.rb",
    "lib/digest_mailer/models/digest_type.rb",
    "lib/digest_mailer/models/email_digest.rb",
    "lib/digest_mailer/models/email_log.rb",
    "lib/digest_mailer/models/email_message.rb",
    "lib/digest_mailer/models/non_user_recipient.rb",
    "lib/digest_mailer/models/pending_digest_message.rb",
    "lib/digest_mailer/models/pending_message.rb",
    "lib/digest_mailer/version.rb",
    "log/placeholder.txt",
    "recipes/digest_mailer.rb",
    "spec/factories/digest_type.rb",
    "spec/factories/email_digest.rb",
    "spec/factories/email_log.rb",
    "spec/factories/email_message.rb",
    "spec/factories/idea.rb",
    "spec/factories/membership.rb",
    "spec/factories/project.rb",
    "spec/factories/role.rb",
    "spec/factories/user.rb",
    "spec/mail_logger_spec.rb",
    "spec/mail_orchestrator_spec.rb",
    "spec/models/digest_type_spec.rb",
    "spec/models/email_digest_spec.rb",
    "spec/models/email_log_spec.rb",
    "spec/models/email_message_spec.rb",
    "spec/models/pending_message_spec.rb",
    "spec/models/user_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/szehnder/digest_mailer}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.7.2}
  s.summary = %q{Provides a digest functionality for our app}
  s.test_files = [
    "spec/factories/digest_type.rb",
    "spec/factories/email_digest.rb",
    "spec/factories/email_log.rb",
    "spec/factories/email_message.rb",
    "spec/factories/idea.rb",
    "spec/factories/membership.rb",
    "spec/factories/project.rb",
    "spec/factories/role.rb",
    "spec/factories/user.rb",
    "spec/mail_logger_spec.rb",
    "spec/mail_orchestrator_spec.rb",
    "spec/models/digest_type_spec.rb",
    "spec/models/email_digest_spec.rb",
    "spec/models/email_log_spec.rb",
    "spec/models/email_message_spec.rb",
    "spec/models/pending_message_spec.rb",
    "spec/models/user_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<digest_mailer>, [">= 0"])
      s.add_runtime_dependency(%q<delayed_job>, [">= 0"])
      s.add_runtime_dependency(%q<mysql2>, [">= 0"])
      s.add_development_dependency(%q<rails>, ["~> 3.0"])
      s.add_development_dependency(%q<rspec>, ["~> 2.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<sqlite3>, [">= 0"])
      s.add_development_dependency(%q<factory_girl>, [">= 0"])
      s.add_development_dependency(%q<ZenTest>, [">= 0"])
      s.add_development_dependency(%q<database_cleaner>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<digest_mailer>, [">= 0"])
      s.add_dependency(%q<delayed_job>, [">= 0"])
      s.add_dependency(%q<mysql2>, [">= 0"])
      s.add_dependency(%q<rails>, ["~> 3.0"])
      s.add_dependency(%q<rspec>, ["~> 2.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<factory_girl>, [">= 0"])
      s.add_dependency(%q<ZenTest>, [">= 0"])
      s.add_dependency(%q<database_cleaner>, [">= 0"])
      s.add_dependency(%q<ruby-debug19>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<digest_mailer>, [">= 0"])
    s.add_dependency(%q<delayed_job>, [">= 0"])
    s.add_dependency(%q<mysql2>, [">= 0"])
    s.add_dependency(%q<rails>, ["~> 3.0"])
    s.add_dependency(%q<rspec>, ["~> 2.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<factory_girl>, [">= 0"])
    s.add_dependency(%q<ZenTest>, [">= 0"])
    s.add_dependency(%q<database_cleaner>, [">= 0"])
    s.add_dependency(%q<ruby-debug19>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

