sqlite3:
  adapter: sqlite3
  database: digest_mailer.sqlite3

mysql2:
  adapter: mysql2
  host: victors-stage.cr8guujt7srm.us-east-1.rds.amazonaws.com
  username: victors
  password: kraftwerk77
  database: digest_mailer_test
  pool: 5
  port: 3306